# working with cdds=1.0.5
---
name: cdds
channels:
  - conda-forge
  - defaults
dependencies:
  - cmor
  - scipy=1.1.0
  - nc-time-axis=1.1.0
  - netcdf4=1.3.1
  - cftime=1.0.1
  - cartopy=0.16.0
  - iris=1.13
  - mock
  - configparser
  - jinja2
  - mysql-python
  - pep8
  - filelock
  - pip:
    - dreqpy
    - regrid2
